from .rng import DeterministicRNG

_WIN_TEMPLATES = [
    "A decisive Win for the squad.",
    "The team secures a hard-fought Win.",
    "An impressive Win that sends a message.",
    "They walk away with a Win this week.",
    "The final whistle seals a Win.",
    "A Win that shifts the momentum.",
    "The scoreboard reflects a Win.",
    "Fans react to a stunning Win.",
    "A Win for the history books.",
    "They earned this Win on the court.",
    "The post-match mood is defined by this Win.",
    "A Win that nobody saw coming.",
    "The expected Win materializes.",
    "A gritty, unpolished Win.",
    "The Win speaks for itself.",
    "They ground out a Win.",
    "A textbook Win from start to finish.",
    "An emotional Win for the locker room.",
    "A Win built on pure effort.",
    "The Win leaves the league buzzing.",
    "A Win driven by late execution.",
    "The Win confirms their status.",
    "A Win that changes the narrative.",
    "They pull off a stunning Win.",
    "A methodical Win executed perfectly.",
    "A Win that defines the season.",
    "The ultimate Win to close the week.",
]

_LOSS_TEMPLATES = [
    "A tough Loss the squad will want to forget.",
    "The team falls to a hard Loss.",
    "A costly Loss that raises questions.",
    "They drop this one — a Loss that stings.",
    "The final whistle seals a damaging Loss.",
    "A Loss that shifts the momentum the wrong way.",
    "The scoreboard reflects a difficult Loss.",
    "A Loss the coaching staff will review carefully.",
    "They come up short — a clear Loss.",
    "The post-match mood is heavy after this Loss.",
    "An unexpected Loss shakes the program.",
    "A Loss that was building all match.",
    "A grinding, painful Loss.",
    "The Loss speaks for itself.",
    "They couldn't hold on — a Loss.",
    "A Loss from start to finish.",
    "An emotional Loss for the locker room.",
    "A Loss built on missed opportunities.",
    "The Loss leaves questions in the league.",
    "A Loss driven by late mistakes.",
    "The Loss puts pressure on the season.",
    "A Loss that changes the narrative.",
    "They couldn't pull it off — a Loss.",
    "A Loss that will sting for days.",
    "The Loss confirms the challengers ahead.",
    "A Loss that defines the stakes.",
    "The final Loss to close a hard week.",
]


def render_headline(result: str, context: str, rng: DeterministicRNG, **kwargs) -> str:
    templates = _WIN_TEMPLATES if result == "Win" else _LOSS_TEMPLATES
    return rng.choice(templates)
